### PR TITLE
Implemented align method for Variable and Expression.

### PR DESCRIPTION
**Pull request by kjartan-at-bravos**
The purpose of this method is to align (and broadcast) an expression so that addition can take place. For instance

`P_l_post_contingency = P_l_basecase.to_expr().align(P_contingency) + P_contingency`

### CODE REVIEW

**Comment by staadecker** [comment]
Thank you Kjartan, are there other use cases you've encountered for this or is it always as a way to add with another expression? Perhaps, broadcasting should automatically happen?

**Comment by kjartan-at-bravos** [comment]
Like `x.broadcast_like(y) + 4*y`

**Comment by kjartan-at-bravos** [comment]
Possibly, the proposed method implemented in this PR should have a more descriptive name. Like `align_and_broadcast_like`. Longer and uglier, but more descriptive, as stated. 

Along the same line of thought, maybe the operation should be divided in two. Since one part is broadcasting, and the other is filter so that only coordinates of `other` are kept. The syntax would be
`y.broadcast_like(x).filter_like(x)`

On the other hand, this means doing the join operation with `x.data` twice.

**Comment by staadecker** [comment]
I'm thinking:

`y.broadcast("time").default(0) + someting_with_a_time_dim`

and the `broadcast()` and `default()` only set flags on the y object that say we allow broadcasting in the `time` dimension and any missing indices are assumed to be `0` (i.e. we can auto fill them / ignore them). This way, the `.join` that happens with `+` can handle all the behaviour in one step.

Thoughts?

**Comment by kjartan-at-bravos** [comment]
Sounds like a good solution for the issue of broadcasting!

Just to circle back to the original  motivation for the `.align()` method. The idea is that `x.align(y)` returns only the variables with coordinates  of `x` that are also present in `y`, so that fewer constraints result when doing 
` m.c = (x.align(y) + y <= limit)`. 

These extra constraints that would result from doing `.broadcast()`as you suggest @staadecker  are certainly valid constraints for the model in my case, it is just that they are already defined in the model.

**Comment by staadecker** [comment]
Hmmm I see. I'm not a fan of the term "align" because it's really an xarray concept (which makes me think, maybe broadcast should be called add_dim). Perhaps instead of align a better way of doing things is:

```python3
# y has less indices than x so this would be an error:
# x + y ≤ limit

# But this works and has the shape of x
x + y.fill_missing() ≤ limit

# This also works and has the shape of y
x.drop_missing() + y ≤ limit
```

**Comment by kjartan-at-bravos** [comment]
That's a great solution! It becomes very clear from the syntax what's happening.

**Comment by staadecker** [comment]
See #17 instead

**Pull request closed without merging**
